{% set name = "bcolz-zipline" %}
{% set version = "1.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bcolz_zipline-{{ version }}.tar.gz
  sha256: 196b38c0d810f422374fc84f00139a0c6bc03bd3bdc9def678c09c460d602456

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - toml
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - packaging

test:
  commands:
    - python -c "import bcolz; bcolz.test()"
  requires:
    - numpy
    - setuptools

about:
  home: https://pypi.org/project/bcolz-zipline/
  summary: Columnar and compressed data containers.
  license: BSD-3-Clause
  license_file: LICENSES/BCOLZ.txt

extra:
  recipe-maintainers:
    - stefan-jansen
